export function createBlenderBuildScript() {
	return String.raw`# Generated by CAMERA_FRAMES.
# Run with: blender --background --factory-startup --python build_blend.py
import json
import math
import os
import struct

import bpy
from mathutils import Matrix, Quaternion, Vector

ROOT = os.path.dirname(os.path.abspath(__file__))
MANIFEST_PATH = os.path.join(ROOT, "manifest.json")

with open(MANIFEST_PATH, "r", encoding="utf-8") as handle:
    manifest = json.load(handle)


def absolute_path(relative_path):
    return os.path.normpath(os.path.join(ROOT, relative_path.replace("/", os.sep)))


def safe_name(value, fallback):
    text = str(value or "").strip()
    return text if text else fallback


# Three.js uses Y-up. Blender uses Z-up.
THREE_TO_BLENDER = Matrix.Rotation(math.radians(90.0), 4, "X")


def three_matrix(transform):
    position = transform.get("position") or {}
    rotation = transform.get("quaternion") or {}
    scale = transform.get("scale") or {}
    translation_matrix = Matrix.Translation((
        float(position.get("x", 0.0)),
        float(position.get("y", 0.0)),
        float(position.get("z", 0.0)),
    ))
    quaternion = Quaternion((
        float(rotation.get("w", 1.0)),
        float(rotation.get("x", 0.0)),
        float(rotation.get("y", 0.0)),
        float(rotation.get("z", 0.0)),
    ))
    scale_matrix = Matrix.Diagonal((
        float(scale.get("x", 1.0)),
        float(scale.get("y", 1.0)),
        float(scale.get("z", 1.0)),
        1.0,
    ))
    return translation_matrix @ quaternion.to_matrix().to_4x4() @ scale_matrix


def blender_matrix(transform):
    source_matrix = three_matrix(transform)
    return THREE_TO_BLENDER @ source_matrix @ THREE_TO_BLENDER.inverted()


def add_custom_properties(target, values):
    for key, value in values.items():
        if value is None:
            continue
        if isinstance(value, (dict, list)):
            target[key] = json.dumps(value, ensure_ascii=False)
        else:
            target[key] = value


def parent_imported_roots(objects, root):
    imported = set(objects)
    for obj in objects:
        if root.users_collection[0] not in obj.users_collection:
            root.users_collection[0].objects.link(obj)
        if obj.parent not in imported:
            obj.parent = root


def import_model(asset, collection):
    before = set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=absolute_path(asset["path"]))
    imported = [obj for obj in bpy.data.objects if obj not in before]
    root = bpy.data.objects.new(safe_name(asset.get("name"), "Model"), None)
    collection.objects.link(root)
    parent_imported_roots(imported, root)
    root.matrix_world = blender_matrix(asset["transform"])
    root.hide_render = not bool(asset.get("visible", True))
    root.hide_viewport = not bool(asset.get("visible", True))
    add_custom_properties(root, {
        "camera_frames_asset_id": asset.get("id"),
        "camera_frames_kind": "model",
        "camera_frames_source": asset.get("path"),
        "camera_frames_export_role": asset.get("exportRole"),
    })
    return root


def read_glb(path):
    with open(path, "rb") as handle:
        data = handle.read()
    magic, version, total_length = struct.unpack_from("<III", data, 0)
    if magic != 0x46546C67 or version != 2 or total_length > len(data):
        raise ValueError("Unsupported GLB: " + path)
    offset = 12
    document = None
    binary = b""
    while offset + 8 <= total_length:
        chunk_length, chunk_type = struct.unpack_from("<II", data, offset)
        offset += 8
        chunk = data[offset:offset + chunk_length]
        offset += chunk_length
        if chunk_type == 0x4E4F534A:
            document = json.loads(chunk.decode("utf-8").rstrip(" \t\r\n\x00"))
        elif chunk_type == 0x004E4942:
            binary = chunk
    if document is None:
        raise ValueError("GLB has no JSON chunk: " + path)
    return document, binary


COMPONENT_FORMATS = {
    5120: ("b", 1),
    5121: ("B", 1),
    5122: ("h", 2),
    5123: ("H", 2),
    5125: ("I", 4),
    5126: ("f", 4),
}
TYPE_COMPONENTS = {
    "SCALAR": 1,
    "VEC2": 2,
    "VEC3": 3,
    "VEC4": 4,
}


def normalize_component(value, component_type):
    if component_type == 5120:
        return max(float(value) / 127.0, -1.0)
    if component_type == 5121:
        return float(value) / 255.0
    if component_type == 5122:
        return max(float(value) / 32767.0, -1.0)
    if component_type == 5123:
        return float(value) / 65535.0
    return float(value)


def read_accessor(document, binary, accessor_index):
    accessor = document["accessors"][accessor_index]
    view = document["bufferViews"][accessor["bufferView"]]
    component_type = accessor["componentType"]
    fmt, component_size = COMPONENT_FORMATS[component_type]
    component_count = TYPE_COMPONENTS[accessor["type"]]
    element_size = component_size * component_count
    stride = int(view.get("byteStride", element_size))
    offset = int(view.get("byteOffset", 0)) + int(accessor.get("byteOffset", 0))
    normalized = bool(accessor.get("normalized", False))
    output = []
    for index in range(int(accessor["count"])):
        values = struct.unpack_from(
            "<" + (fmt * component_count),
            binary,
            offset + index * stride,
        )
        if normalized:
            values = tuple(normalize_component(value, component_type) for value in values)
        output.append(values if component_count > 1 else values[0])
    return output


def get_splat_attributes(document):
    primitive = document["meshes"][0]["primitives"][0]
    extension = primitive.get("extensions", {}).get("KHR_gaussian_splatting")
    if extension is None:
        raise ValueError("KHR_gaussian_splatting is missing")
    return primitive["attributes"]


def import_splat(asset, collection):
    source_path = absolute_path(asset["path"])
    document, binary = read_glb(source_path)
    attributes = get_splat_attributes(document)
    positions = read_accessor(document, binary, attributes["POSITION"])
    colors = read_accessor(document, binary, attributes["COLOR_0"])
    scales = read_accessor(
        document,
        binary,
        attributes["KHR_gaussian_splatting:SCALE"],
    )

    point_cloud = bpy.data.pointclouds.new(safe_name(asset.get("name"), "Gaussian Splat"))
    point_cloud.points.add(len(positions))
    converted_positions = []
    radii = []
    rgba = []
    for position, scale, color in zip(positions, scales, colors):
        converted_positions.extend((position[0], -position[2], position[1]))
        radii.append(max(math.exp(scale[0]), math.exp(scale[1]), math.exp(scale[2])))
        if len(color) == 3:
            rgba.extend((color[0], color[1], color[2], 1.0))
        else:
            rgba.extend((color[0], color[1], color[2], color[3]))
    point_cloud.points.foreach_set("co", converted_positions)
    radius_attribute = point_cloud.attributes.get("radius")
    if radius_attribute is None:
        radius_attribute = point_cloud.attributes.new("radius", "FLOAT", "POINT")
    radius_attribute.data.foreach_set("value", radii)
    color_attribute = point_cloud.color_attributes.get("color")
    if color_attribute is None:
        color_attribute = point_cloud.color_attributes.new(
            name="color",
            type="FLOAT_COLOR",
            domain="POINT",
        )
    color_attribute.data.foreach_set("color", rgba)

    obj = bpy.data.objects.new(safe_name(asset.get("name"), "Gaussian Splat"), point_cloud)
    collection.objects.link(obj)
    obj.matrix_world = blender_matrix(asset["transform"])
    obj.hide_render = not bool(asset.get("visible", True))
    obj.hide_viewport = not bool(asset.get("visible", True))
    add_custom_properties(obj, {
        "camera_frames_asset_id": asset.get("id"),
        "camera_frames_kind": "gaussian-splat",
        "camera_frames_source": asset.get("path"),
        "camera_frames_khr_extension": "KHR_gaussian_splatting",
        "camera_frames_proxy": "Blender PointCloud",
        "camera_frames_fidelity": asset.get("fidelity"),
        "camera_frames_splat_count": asset.get("splatCount"),
        "camera_frames_export_role": asset.get("exportRole"),
    })
    return obj


def apply_animation(target, samples):
    if not samples:
        return
    target.rotation_mode = "QUATERNION"
    for sample in samples:
        target.matrix_world = blender_matrix(sample["transform"])
        target.keyframe_insert(data_path="location", frame=sample["frame"])
        target.keyframe_insert(data_path="rotation_quaternion", frame=sample["frame"])
        target.keyframe_insert(data_path="scale", frame=sample["frame"])


def configure_camera_data(camera_data, camera_record):
    frustum = camera_record["frustum"]
    near = max(float(camera_record.get("near", 0.1)), 1e-6)
    width = max(float(frustum["right"]) - float(frustum["left"]), 1e-6)
    height = max(float(frustum["top"]) - float(frustum["bottom"]), 1e-6)
    camera_data.type = "PERSP"
    camera_data.sensor_fit = "HORIZONTAL"
    camera_data.sensor_width = 36.0
    camera_data.lens = 36.0 * near / width
    camera_data.shift_x = -(float(frustum["left"]) + float(frustum["right"])) / (2.0 * width)
    camera_data.shift_y = -(float(frustum["bottom"]) + float(frustum["top"])) / (2.0 * height)
    camera_data.clip_start = near
    camera_data.clip_end = max(float(camera_record.get("far", 1000.0)), near + 1e-3)
    add_custom_properties(camera_data, {
        "camera_frames_frustum": frustum,
        "camera_frames_output_size": camera_record.get("output"),
    })


def attach_reference_backgrounds(camera_data, camera_record):
    camera_data.show_background_images = True
    for reference in camera_record.get("references", []):
        try:
            background = camera_data.background_images.new()
            background.image = bpy.data.images.load(
                absolute_path(reference["path"]),
                check_existing=True,
            )
            background.alpha = float(reference.get("opacity", 1.0))
            background.display_depth = "BACK" if reference.get("group") == "back" else "FRONT"
        except Exception as error:
            print("Reference image warning:", error)


def create_camera_scene(camera_record, content_collection, world):
    camera_name = safe_name(camera_record.get("name"), "Camera")
    camera_data = bpy.data.cameras.new(camera_name)
    configure_camera_data(camera_data, camera_record)
    camera_object = bpy.data.objects.new(camera_name, camera_data)
    content_collection.objects.link(camera_object)
    camera_object.matrix_world = blender_matrix(camera_record["transform"])
    attach_reference_backgrounds(camera_data, camera_record)
    add_custom_properties(camera_object, {
        "camera_frames_camera_id": camera_record.get("id"),
        "camera_frames_references": camera_record.get("references", []),
    })

    scene = bpy.data.scenes.new(camera_name)
    scene.collection.children.link(content_collection)
    scene.camera = camera_object
    scene.world = world
    output = camera_record.get("output", {})
    scene.render.resolution_x = int(output.get("width", 1920))
    scene.render.resolution_y = int(output.get("height", 1080))
    scene.render.resolution_percentage = 100
    scene.render.film_transparent = True
    animation = manifest.get("animation") or {}
    scene.render.fps = int(animation.get("fps", 24))
    scene.frame_start = int(animation.get("startFrame", 1))
    scene.frame_end = int(animation.get("endFrame", scene.frame_start))

    samples = camera_record.get("animation") or []
    if samples:
        camera_object.rotation_mode = "QUATERNION"
        for sample in samples:
            camera_object.matrix_world = blender_matrix(sample["transform"])
            configure_camera_data(camera_data, sample)
            frame = int(sample["frame"])
            camera_object.keyframe_insert(data_path="location", frame=frame)
            camera_object.keyframe_insert(data_path="rotation_quaternion", frame=frame)
            camera_data.keyframe_insert(data_path="lens", frame=frame)
            camera_data.keyframe_insert(data_path="shift_x", frame=frame)
            camera_data.keyframe_insert(data_path="shift_y", frame=frame)
    return scene


def configure_world(lighting):
    world = bpy.data.worlds.new("CAMERA_FRAMES World")
    world.use_nodes = True
    background = world.node_tree.nodes.get("Background")
    ambient = max(float(lighting.get("ambient", 0.35)), 0.0)
    background.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    background.inputs["Strength"].default_value = ambient
    return world


def add_sun(lighting, collection):
    model_light = lighting.get("modelLight") or {}
    if not model_light.get("enabled", True):
        return
    data = bpy.data.lights.new("CAMERA_FRAMES Sun", type="SUN")
    data.energy = max(float(model_light.get("intensity", 1.0)), 0.0)
    obj = bpy.data.objects.new("CAMERA_FRAMES Sun", data)
    collection.objects.link(obj)
    azimuth = math.radians(float(model_light.get("azimuthDeg", -35.0)))
    elevation = math.radians(float(model_light.get("elevationDeg", 45.0)))
    direction = (
        math.cos(elevation) * math.sin(azimuth),
        -math.cos(elevation) * math.cos(azimuth),
        math.sin(elevation),
    )
    obj.rotation_euler = Vector((0.0, 0.0, -1.0)).rotation_difference(
        Vector(direction)
    ).to_euler()


bpy.ops.wm.read_factory_settings(use_empty=True)
content = bpy.data.collections.new("CAMERA_FRAMES Content")
world = configure_world(manifest.get("lighting") or {})
add_sun(manifest.get("lighting") or {}, content)

asset_objects = {}
for asset in manifest.get("assets", []):
    try:
        if asset.get("kind") == "splat":
            obj = import_splat(asset, content)
        else:
            obj = import_model(asset, content)
        asset_objects[str(asset.get("id"))] = obj
        apply_animation(obj, asset.get("animation") or [])
    except Exception as error:
        print("Asset import failed:", asset.get("name"), error)

scenes = []
for camera_record in manifest.get("cameras", []):
    scenes.append(create_camera_scene(camera_record, content, world))

if not scenes:
    fallback_scene = bpy.data.scenes.new("CAMERA_FRAMES")
    fallback_scene.collection.children.link(content)
    fallback_scene.world = world
    scenes.append(fallback_scene)

for scene in list(bpy.data.scenes):
    if scene not in scenes:
        bpy.data.scenes.remove(scene)

output_path = absolute_path(manifest.get("blendFile", "camera-frames.blend"))
if bpy.context.window is not None:
    bpy.context.window.scene = scenes[0]
bpy.ops.wm.save_as_mainfile(filepath=output_path)
print("CAMERA_FRAMES Blender package created:", output_path)
`;
}

export function createBlenderLauncher({
	blendFile = "camera-frames.blend",
} = {}) {
	const normalizedBlendFile = String(
		blendFile ?? "camera-frames.blend",
	).replace(/"/g, "");
	return `@echo off
setlocal
set "ROOT=%~dp0"
set "BLENDER="
where blender.exe >nul 2>nul && set "BLENDER=blender.exe"
if not defined BLENDER (
  for /d %%D in ("%ProgramFiles%\\Blender Foundation\\Blender *") do (
    if exist "%%~fD\\blender.exe" set "BLENDER=%%~fD\\blender.exe"
  )
)
if not defined BLENDER (
  echo Blender was not found. Install Blender or add blender.exe to PATH.
  pause
  exit /b 1
)
"%BLENDER%" --background --factory-startup --python "%ROOT%build_blend.py"
if errorlevel 1 (
  echo Blender package creation failed.
  pause
  exit /b 1
)
start "" "%BLENDER%" "%ROOT%${normalizedBlendFile}"
endlocal
`;
}

export function createBlenderPackageReadme({
	appVersion = "0.0.0",
	blendFile = "camera-frames.blend",
} = {}) {
	return `CAMERA_FRAMES Blender Package
Generated by CAMERA_FRAMES ${appVersion}

Quick start
1. Extract this ZIP completely.
2. Double-click open_in_blender.cmd.
3. The script creates ${blendFile} and opens it in Blender.

Package contract
- Models are stored as standard GLB files.
- Every 3DGS asset is stored as a GLB using KHR_gaussian_splatting.
- build_blend.py reconstructs scene transforms, cameras, output sizes, lighting,
  camera background images, and baked transform/lens animation.
- No Blender add-on is installed or required.

3DGS note
Blender does not render KHR_gaussian_splatting natively. The script creates a
Blender PointCloud proxy for inspection and keeps each KHR GLB as the source of
truth. The proxy uses the exported DC color and the largest Gaussian axis as
its point radius. Gaussian anisotropy and view-dependent higher-order SH are
not reproduced by the standard PointCloud renderer.

Reference image note
Reference images are attached to their cameras as Blender background images.
Their exact CAMERA_FRAMES layout metadata is also stored on the camera object.
Background images are viewport guides and are not composited into Blender
renders automatically.
`;
}
